#!/usr/bin/env bash
# Install nginx server with modifications

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
str_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$str_replace/" /etc/nginx/sites-enabled/default

sudo service nginx start
