#!/usr/bin/env bash
# Install nginx server with modifications

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
str_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$str_replace/" /etc/nginx/sites-enabled/default

# Custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
str_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$str_replace/" /etc/nginx/sites-enabled/default

sudo service nginx start
