#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header on web-01 and web-02
# The name of the custom HTTP header should be X-Served-By and its value should be the
# hostname of the server Nginx is running on

sudo apt-get update
sudo apt-get -y install nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# Change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

# Create home page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirect traffic going to /redirect_me
str_replace="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$str_replace/" /etc/nginx/sites-enabled/default

# Custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure redirect for custom 404 page
str_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$str_replace/" /etc/nginx/sites-enabled/default

# Start service
sudo service nginx restart
