#!/usr/bin/env bash
# Bash init script for manage_my_process

if [[ $1 == "start" ]]; then
	./manage_my_process &
	pid=$(pgrep -f manage_my_process)
	echo "$pid" > "/var/run/my_process.pid"
	echo "manage_my_process started"
elif [[ $1 == "stop" ]]; then
	pkill -f manage_my_process
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [[ $1 == "restart" ]]; then
	pkill -f manage_my_process
	rm -f /var/run/my_process.pid
	./manage_my_process &
	pid=$(pgrep -f manage_my_process)
        echo "$pid" > "/var/run/my_process.pid"
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
