#!/usr/bin/env bash
# Print out "To infinity and beyond" infinitely and trap SIGTERM
# printing out "I am invincible!!!" after receiving SIGTERM

trap "echo I am invincible!!!" SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
