#!/usr/bin/env bash
# Bash script that prints content of /etc/passwd
# Output only contains username, user id and home directory path for user

filename="/etc/passwd"
while read line; do
	echo "$line" | cut -d ":" -f 1,3,7
	n=$((n+1))
done < $filename
