#!/usr/bin/env bash
# Bash script that displays "Best School" 10 times using while loop
# After the 9th line, print "Hi"
i="0"
while [ $i -lt 10 ]
    do
	echo "Best School"
	i=$((i + 1))
	if (("$i" == "9")); then
		echo "Hi"
	fi
done
