#!/usr/bin/env bash
# Script to print out the time for 12 hours and 59 minutes

hours=0
minutes=0
while ((hours < 13 || minutes < 60 )); do
	# Convert 60 to 0 for minutes
	if [ "$minutes" -eq "60" ]; then
		minutes=0
	fi

	# Print hours if minutes is 0
	if [ "$minutes" -eq "0" ]; then
		echo "Hour: $hours"
		((hours++))
	else
		echo "$minutes"
	fi
	((minutes++))
done
