#!/usr/bin/env bash
# Container fix to run nginx as user 'nginx'
chmod 644 /etc/nginx/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
